In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('codis_C0F9Y0_weather_data.csv')
df.head(10)

,StationID,date,hour,StationPressure_Instantaneous,AirTemperature_Instantaneous,RelativeHumidity_Instantaneous,WindSpeed_Mean,WindDirection_Mean,PeakGust_Maximum,PeakGust_Direction,...,Precipitation_Accumulation,Precipitation_MeltFlag,SunshineDuration_Total,GlobalSolarRadiation_Accumulation,SoilTemperatureAt0cm_Instantaneous,SoilTemperatureAt5cm_Instantaneous,SoilTemperatureAt10cm_Instantaneous,SoilTemperatureAt20cm_Instantaneous,SoilTemperatureAt50cm_Instantaneous,SoilTemperatureAt100cm_Instantaneous
0,C0F9Y0,2016-04-29,01:00:00,685.0,4.5,96.0,2.9,257.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C0F9Y0,2016-04-29,02:00:00,684.7,4.6,88.0,4.8,239.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C0F9Y0,2016-04-29,03:00:00,684.3,4.6,69.0,6.1,240.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C0F9Y0,2016-04-29,04:00:00,684.4,4.7,61.0,5.5,234.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C0F9Y0,2016-04-29,05:00:00,684.5,5.1,50.0,5.0,248.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,C0F9Y0,2016-04-29,06:00:00,684.8,4.7,46.0,5.3,231.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,C0F9Y0,2016-04-29,07:00:00,685.3,4.6,53.0,5.0,233.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,C0F9Y0,2016-04-29,08:00:00,685.8,6.1,62.0,2.9,245.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,C0F9Y0,2016-04-29,09:00:00,686.2,6.1,70.0,4.0,221.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,C0F9Y0,2016-04-29,10:00:00,686.4,8.3,74.0,2.6,231.0,NaN,NaN,...,-999.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_cleaner = df[['StationID', 'date', 'hour', 'AirTemperature_Instantaneous', 'RelativeHumidity_Instantaneous','Precipitation_Accumulation']]
df_cleaner.head(10)

,StationID,date,hour,AirTemperature_Instantaneous,RelativeHumidity_Instantaneous,Precipitation_Accumulation
0,C0F9Y0,2016-04-29,01:00:00,4.5,96.0,-999.6
1,C0F9Y0,2016-04-29,02:00:00,4.6,88.0,-999.6
2,C0F9Y0,2016-04-29,03:00:00,4.6,69.0,-999.6
3,C0F9Y0,2016-04-29,04:00:00,4.7,61.0,-999.6
4,C0F9Y0,2016-04-29,05:00:00,5.1,50.0,-999.6
5,C0F9Y0,2016-04-29,06:00:00,4.7,46.0,-999.6
6,C0F9Y0,2016-04-29,07:00:00,4.6,53.0,-999.6
7,C0F9Y0,2016-04-29,08:00:00,6.1,62.0,-999.6
8,C0F9Y0,2016-04-29,09:00:00,6.1,70.0,-999.6
9,C0F9Y0,2016-04-29,10:00:00,8.3,74.0,-999.6